# AQRUIVO DE CONFIGURAÇÃO

# PERMIÇÃO PARA STACKAR POÇÕES
stack-permission: "stack.permission"

# QUANTIDADE MÁXIMA QUE UMA POÇÃO IRÁ STACKAR
max-potion-stack: 64

# STACK ITEM:
stack-item:
  item: "450:1"
  name: "Agrupar Poções"

# CRIE POÇÕES CUSTOMIZADAS...
custom-potions:
  99:                                 # META OU DAMAGE, PARA O /GIVE
    displayName: "Poção de Força III" # NOME DA POÇÃO
    effects:                          # EFEITOS...
      - effect: 5                     # ID DO EFEITO
        name: "Força"                 # (Opcional) NOME DO EFEITO
        amplifier: 3                  # AMPLIFIER
        duration: 120                 # DURAÇÃO EM SEGUNDOS
  100:
    displayName: "Poção de Velocidade III"
    effects:
      - effect: 1
        name: "Velocidade"
        amplifier: 10
        duration: 120
  101:
    displayName: "Poção do Capiroto I"
    effects:
      - effect: 5
        name: "Força"
        amplifier: 10
        duration: 120
      - effect: 1
        name: "Velocidade"
        amplifier: 10
        duration: 120
